pmain                res     300
zmain                res     4
offset0              res     4
literal0             res     4
literal1             res     4
literal2             res     4
literal3             res     4
literal4             res     4
offset1              res     4
literal5             res     4
literal6             res     4
literal7             res     4
literal8             res     4
literal9             res     4
offset2              res     4
literal10            res     4
literal11            res     4
literal12            res     4
literal13            res     4
literal14            res     4
offset3              res     4
literal15            res     4
literal16            res     4
literal17            res     4
literal18            res     4
literal19            res     4
offset4              res     4
literal20            res     4
literal21            res     4
literal22            res     4
literal23            res     4
literal24            res     4
offset5              res     4
literal25            res     4
literal26            res     4
literal27            res     4
literal28            res     4
literal29            res     4
offset6              res     4
literal30            res     4
literal31            res     4
literal32            res     4
literal33            res     4
offset7              res     4
literal34            res     4
literal35            res     4
literal36            res     4
literal37            res     4
offset8              res     4
literal38            res     4
literal39            res     4
literal40            res     4
literal41            res     4
offset9              res     4
literal42            res     4
literal43            res     4
literal44            res     4
literal45            res     4
offset10             res     4
buffer               res     200
stackbase            res     2048
