zmain                res     4
offset0              res     4
literal0             res     4
literal1             res     4
tempVar0             res     4
literal2             res     4
tempVar1             res     4
literal3             res     4
tempVar2             res     4
literal4             res     4
tempVar3             res     4
literal5             res     4
literal6             res     4
literal7             res     4
tempVar4             res     4
tempVar5             res     4
literal8             res     4
literal9             res     4
tempVar6             res     4
tempVar7             res     4
tempVar8             res     4
literal10            res     4
tempVar9             res     4
literal11            res     4
literal12            res     4
tempVar10            res     4
literal13            res     4
tempVar11            res     4
literal14            res     4
tempVar12            res     4
tempVar13            res     4
literal15            res     4
literal16            res     4
tempVar14            res     4
tempVar15            res     4
offset1              res     4
literal17            res     4
literal18            res     4
tempVar16            res     4
offset2              res     4
buffer               res     200
stackbase            res     2048
